# Linear Regression Example

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

Assume we have data, where y = salary and X is a matrix containing two columns, the first column shows how many years the person has studied and the second columns shows how many years of experience the person has. 

# Estimating a simple linear regression model.

In [2]:
X = np.array([[5, 2], [3, 4], [2, 7], [0, 10]])
y_true = np.array([34000, 31000, 33000, 28000])

In [3]:
print(X)
print()
print(y_true)

[[ 5  2]
 [ 3  4]
 [ 2  7]
 [ 0 10]]

[34000 31000 33000 28000]


In [4]:
# 1. Initialize the model. 
lin_reg = LinearRegression(fit_intercept=False)

In [5]:
# 2. Fit the model. 
lin_reg = lin_reg.fit(X, y_true)

In [6]:
print(lin_reg.coef_)
print(lin_reg.intercept_)

[5909.67616075 2900.89738588]
0.0


In [7]:
# 3. Predicting the train data.
y_pred = lin_reg.predict(X)
print('predictions', y_pred)
print('true y', y_true)

predictions [35350.1755755  29332.61802575 32125.63402263 29008.97385876]
true y [34000 31000 33000 28000]


In [8]:
# Predicting "new data" where we want to predict the salary y which in reality is unknow now. 

In [9]:
X_new = np.array([[7, 3]])
y_pred_new = lin_reg.predict(X_new)
y_pred_new

array([50070.42528287])

In [11]:
# Look at hyperparameters, we used all the default values in this case. 
lin_reg.get_params()

{'copy_X': True,
 'fit_intercept': False,
 'n_jobs': None,
 'normalize': 'deprecated',
 'positive': False}

## Calculate Root Mean Squared Error (RMSE) for the training data

In [12]:
# Hyperparameter squared=False gives the root mean squared error. 
print(mean_squared_error(y_true, y_pred, squared=False))

1263.49523572137


In [13]:
# Calulating the root mean squared error manually. 
(np.mean(((y_pred - y_true)**2)))**0.5

1263.49523572137


### Vad är RMSE?

RMSE står för Root Mean Squared Error.\
Det är ett mått för att utvärdera regressionsproblem och mäter prediktionernas medelavstånd från de äkta, observerade värdena.

Matematiska formeln för RMSE är:

$RMSE = \sqrt{\frac{1} {n} \sum_{i=1}^{n}(\hat{y}_i-y_i)^2}$

Idén bakom RMSE är simpel:
- Man tar skillnaden mellan en prediktion och respektive observerad värde: $\hat{y}_i-y_i$;    Det kallas för __Error__.
- Vi bryr oss inte om det är en positiv eller negativ skillnad, därför kvadrerar vi: $(\hat{y}_i-y_i)^2$;   Det kallas för __Squared Error__.
- Vi räknar ut medelvärdet för Squared Error: $\frac{1} {n} \sum_{i=1}^{n}(\hat{y}_i-y_i)^2$;    Det kallas för __Mean Squared Error__.
- Vi tar roten ur Mean Squared Error, så måttet är på det samma skala som datan och därför lättare att tolka: $\sqrt{\frac{1} {n} \sum_{i=1}^{n}(\hat{y}_i-y_i)^2}$